[package]
name = "libmaccas"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "McDonald's API Client"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

reqwest = { workspace = true }
uuid = { version = "1.5.0", features = ["v4"] }
http = "1.0"
reqwest-middleware = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
