[package]
name = "dynamodb-migration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
aws-sdk-dynamodb = "1.0.0"
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
tokio = { version = "1.29.1", features = ["macros"] }
anyhow = "1.0.72"
serde_json = "1.0.104"
aws-config = "1.0.3"
sea-orm = { workspace = true }
entity = { workspace = true }
chrono = { workspace = true }
