[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
entity = { workspace = true }

[dependencies.sea-orm-migration]
version = "0.12.14"
features = ["sqlx-postgres", "runtime-tokio-native-tls"]
