[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmaccas = "0.7.6"
simple-dispatcher = "0.3.1"

lambda_runtime = "0.5.1"
lambda_http = "0.5.1"
serde = "1.0.126"
serde_json = "1.0.82"
serde_derive = "1.0.136"
openssl = { version = "0.10", features = ["vendored"] }
aws-sdk-dynamodb = "0.12.0"
config = { version = "0.13.1", features = ["yaml"] }
uuid = { version = "1.1.2", features = ["v4"] }
http-auth-basic = "0.3.3"
aws-config = "0.12.0"
http = "0.2.6"
chrono = "0.4.19"
aws-sdk-s3 = "0.12.0"
aws-types = "0.12.0"
reqwest = { version = "0.11.10", features = ["json", "gzip"] }
reqwest-middleware = "0.1.5"
reqwest-retry = "0.1.4"
tokio-stream = "0.1.8"
log = "0.4.0"
serde_dynamo = { version = "4.0.1", features = ["aws-sdk-dynamodb+0_12"] }
async-trait = "0.1.56"
task-local-extensions = "0.1.1"
reqwest-tracing = "0.3.0"
simplelog = "0.12.0"
jwt = "0.16.0"
rand = "0.8.5"
itertools = "0.10.3"
ts-rs = "6.1"
tokio = "1.6.1"
chrono-tz = "0.6.1"
rust-crypto = "0.2.36"

[lib]
name = "libapi"
path = "src/libapi/lib.rs"

[[bin]]
name = "api"
path = "src/api.rs"

[[bin]]
name = "service"
path = "src/service.rs"
