[package]
name = "maccas-api"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmaccas = "0.16.0"
simple-dispatcher = "0.5.0"

lambda_runtime = "0.5.1"
lambda_http = "0.5.1"
serde = "1.0.139"
serde_json = "1.0.82"
serde_derive = "1.0.136"
openssl = { version = "0.10", features = ["vendored"] }
aws-sdk-dynamodb = "0.15.0"
config = { version = "0.13.1", features = ["yaml"] }
uuid = { version = "1.1.2", features = ["v4"] }
aws-config = "0.15.0"
http = "0.2.6"
chrono = "0.4.19"
aws-sdk-s3 = "0.15.0"
aws-types = "0.15.0"
reqwest = { version = "0.11.10", features = ["json", "gzip"] }
reqwest-middleware = "0.1.5"
reqwest-retry = "0.1.4"
tokio-stream = "0.1.8"
log = "0.4.0"
serde_dynamo = { version = "4.0.3", features = ["aws-sdk-dynamodb+0_15"] }
async-trait = "0.1.56"
task-local-extensions = "0.1.1"
reqwest-tracing = "0.3.0"
jwt = "0.16.0"
rand = "0.8.5"
itertools = "0.10.3"
ts-rs = "6.1"
tokio = "1.20.0"
chrono-tz = "0.6.1"
rust-crypto = "0.2.36"
mime = "0.3.16"
anyhow = "1.0.58"
# for webhook models
twilight-model = "0.11.2"
twilight-util = { version = "0.11.1", features = ["builder"] }
fern = "0.6.1"
utoipa = "1.1.0"
# imap = "3.0.0-alpha.7"
# regex = "1.6.0"

[build-dependencies]
vergen = "7.2.1"

[lib]
name = "libapi"
path = "src/lib/lib.rs"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "service"
path = "src/bin/service.rs"

# [[bin]]
# name = "accounts"
# path = "src/bin/accounts.rs"
