[workspace]
resolver = "2"
members = [
    "api",
    "migration",
    "libmaccas",
    "places",
    "dynamodb-migration",
    "batch",
    "prisma",
    "prisma-cli",
]

[profile.release-strip]
inherits = "release"
strip = "symbols"

[workspace.dependencies]
async-graphql = "6.0.11"

serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"

chrono = "0.4.31"

tracing = "0.1.40"
tracing-subscriber = "0.3.18"

sea-orm = { version = "0.12", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
] }

anyhow = "1.0.75"

config = "0.13.4"

entity = { path = "./entity" }
libmaccas = { path = "./libmaccas" }

thiserror = "1.0.50"
futures = "0.3.29"

prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.10", default-features = false, features = [
    "migrations",
    "postgresql",
] }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.10", default-features = false, features = [
    "migrations",
    "postgresql",
] }
