[workspace]
resolver = "2"
members = [
    "maccas",
    "accounts-cli",
    "libs/foundation",
    "libs/libmaccas-rs",
    "libs/places-rs",
]

[profile.release-strip]
inherits = "release"
strip = "symbols"
