[package]
name = "maccas-api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libmaccas = "0.24.0"

lambda_runtime = "0.6.0"
lambda_http = "0.6.0"
aws-sdk-dynamodb = "0.16.0"
aws-config = "0.46.0"
aws-sdk-s3 = "0.16.0"
aws-types = "0.46.0"

serde = "1.0.139"
serde_json = "1.0.82"
serde_derive = "1.0.136"
serde_dynamo = { version = "4.0.4", features = ["aws-sdk-dynamodb+0_16"] }

twilight-model = "0.12.2"
twilight-util = { version = "0.12.1", features = ["builder"] }

rocket_lamb = { git = "https://github.com/Accurate0/rocket-lamb.git", rev = "044ac92" }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", branch = "master" }

openssl = { version = "0.10", features = ["vendored"] }
config = { version = "0.13.1", features = ["yaml"] }
uuid = { version = "1.1.2", features = ["v4"] }
http = "0.2.6"
chrono = "0.4.19"
reqwest = { version = "0.11.10", features = ["json", "gzip"] }
reqwest-middleware = "0.1.5"
reqwest-retry = "0.1.4"
tokio-stream = "0.1.8"
log = "0.4.0"
async-trait = "0.1.57"
task-local-extensions = "0.1.1"
reqwest-tracing = "0.3.0"
jwt = "0.16.0"
rand = "0.8.5"
itertools = "0.10.3"
ts-rs = "6.1"
tokio = "1.20.1"
chrono-tz = "0.6.3"
rust-crypto = "0.2.36"
mime = "0.3.16"
anyhow = "1.0.58"
fern = "0.6.1"
utoipa = { version = "1.1.0", features = [ "rocket_extras" ] }

[build-dependencies]
vergen = "7.3.2"

# [patch.crates-io]
# libmaccas = { path = "/home/anurag/Projects/libmaccas-rs" }

[lib]
name = "libapi"
path = "src/lib/lib.rs"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "service"
path = "src/bin/service.rs"
