[workspace]
resolver = "2"
members = [
    "api",
    "migration",
    "external/libmaccas",
    "external/places",
    "external/openai",
    "batch",
    "base",
    "event", 
    "sensordata/lib",
]

[profile.release-strip]
inherits = "release"
strip = "symbols"

[workspace.dependencies]
async-graphql = { version = "7.0.6", features = [
    "uuid",
    "chrono",
    "dataloader",
    "log",
    "opentelemetry",
    "tracing",
] }

serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
rand = "0.8.5"
chrono = "0.4.38"

tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-futures = "0.2.5"

sea-orm = { version = "0.12", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
] }

anyhow = "1.0.86"

config = "0.14.0"

entity = { path = "./entity" }
libmaccas = { path = "./external/libmaccas" }
places = { path = "./external/places" }
openai = { path = "./external/openai" }
base = { path = "./base" }
converters = { path = "./converters" }
event = { path = "./event" }
batch = { path = "./batch" }
sensordata = { path = "./sensordata/lib" }

thiserror = "1.0.61"
futures = "0.3.30"
futures-util = "0.3.30"

reqwest = { version = "0.12", features = ["json", "gzip", "native-tls"] }
# https://github.com/open-telemetry/opentelemetry-rust/blob/main/Cargo.toml
reqwest_old = { package = "reqwest", version = "0.11", features = ["json", "gzip", "native-tls"] }
reqwest-middleware = { version = "0.3.2", features = ["json"] }
reqwest-retry = "0.6.0"
reqwest-tracing = { version = "0.5", features = ["opentelemetry_0_23"] }

async-trait = "0.1.80"

tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "sync",
] }
tokio-util = "0.7.11"
cron = "0.12.1"
uuid = { version = "1.9", features = ["v4"] }
redis = { version = "0.25.4", features = [
    "tokio-comp",
    "aio",
    "connection-manager",
] }
axum = { version = "0.7.5", features = ["macros"] }
tower-http = { version = "0.5.2", features = ["trace", "cors"] }
itertools = "0.13.0"
opentelemetry = "0.23.0"
http = "1.1.0"

