[workspace]
resolver = "2"
members = [
    "maccas",
    "accounts-cli",
    "libs/foundation",
    "libs/libmaccas-rs",
    "libs/places-rs",
]

[profile.release-strip]
inherits = "release"
strip = "symbols"

[workspace.dependencies]
aws-sdk-dynamodb = "0.33.0"
aws-sdk-s3 = "0.33.0"
aws-types = "0.56.1"
aws-sdk-sqs = "0.33.0"
aws-sdk-secretsmanager = "0.33.0"
aws-config = { version = "0.56.1" }

serde = "1.0.192"
serde_json = "1.0.108"
serde_derive = "1.0.190"
serde_dynamo = { version = "4.2.9", features = ["aws-sdk-dynamodb+0_33"] }

rocket = { version = "0.5.0-rc.4", features = ["json", "uuid"] }
