[package]
name = "maccas-api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libmaccas = "0.37.0"

lambda_runtime = "0.7.1"
lambda_http = "0.7.1"
aws-sdk-dynamodb = "0.22.0"
aws-config = "0.52.0"
aws-sdk-s3 = "0.22.0"
aws-types = "0.52.0"
aws-sdk-sqs = "0.22.0"
aws-sdk-secretsmanager = "0.22.0"

serde = "1.0.147"
serde_json = "1.0.92"
serde_derive = "1.0.147"
serde_dynamo = { version = "4.0.10", features = ["aws-sdk-dynamodb+0_22"] }
strum = "0.24"
strum_macros = "0.24"

twilight-model = "0.14.0"
twilight-util = { version = "0.14.0", features = ["builder"] }

rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", rev = "54fae07" }

jwt = "0.16.0"
aliri = "0.6.1"
aliri_oauth2 = "0.9.0"
aliri_clock = "0.1.4"

image = "0.24.5"
webp = "0.2.2"

# accounts
regex = "1.7.1"
imap = "2.4.1"
native-tls = "0.2.11"

openssl = { version = "0.10", features = ["vendored"] }
config = { version = "0.13.2", features = ["yaml"] }
uuid = { version = "1.2.2", features = ["v4"] }
http = "0.2.8"
chrono = "0.4.23"
reqwest = { version = "0.11.13", features = ["json", "gzip"] }
reqwest-middleware = "0.2.0"
reqwest-retry = "0.2.1"
tokio-stream = "0.1.11"
log = "0.4.17"
async-trait = "0.1.58"
task-local-extensions = "0.1.3"
reqwest-tracing = "0.4.0"
rand = "0.8.5"
itertools = "0.10.5"
tokio = "1.24.1"
rust-crypto = "0.2.36"
mime = "0.3.16"
anyhow = "1.0.66"
fern = "0.6.1"
utoipa = { version = "2.4.2", features = ["rocket_extras"] }
lazy_static = "1.4.0"
foundation = { git = "https://github.com/Accurate0/foundation.git", tag = "v0.8.1", features = ["discord", "aws", "rocket", "http", "types", "jwt"] }

[build-dependencies]
vergen = "7.4.2"

# [patch.crates-io]
# libmaccas = { path = "/home/anurag/Projects/libmaccas-rs" }

[lib]
name = "maccas"
path = "src/lib.rs"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "refresh"
path = "src/bin/refresh.rs"

[[bin]]
name = "cleanup"
path = "src/bin/cleanup.rs"

[[bin]]
name = "images"
path = "src/bin/images.rs"

[[bin]]
name = "refresh-failure"
path = "src/bin/refresh_failure.rs"

[profile.release-strip]
inherits = "release"
strip = "symbols"
