[package]
name = "maccas-api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libmaccas = "0.30.0"

lambda_runtime = "0.7.0"
lambda_http = "0.7.0"
aws-sdk-dynamodb = "0.19.0"
aws-config = "0.49.0"
aws-sdk-s3 = "0.19.0"
aws-types = "0.49.0"
aws-sdk-sqs = "0.19.0"

serde = "1.0.145"
serde_json = "1.0.85"
serde_derive = "1.0.145"
serde_dynamo = { version = "4.0.8", features = ["aws-sdk-dynamodb+0_19"] }

twilight-model = "0.13.5"
twilight-util = { version = "0.13.3", features = ["builder"] }

rocket_lamb = { git = "https://github.com/Accurate0/rocket-lamb.git", rev = "044ac92" }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", rev = "54fae07" }

jwt = "0.16.0"
jsonwebtoken = "8.1.1"

image = "0.24.4"
webp = "0.2.2"

regex = "1.6.0"
imap = "2.4.1"
native-tls = "0.2.10"

openssl = { version = "0.10", features = ["vendored"] }
config = { version = "0.13.2", features = ["yaml"] }
uuid = { version = "1.1.2", features = ["v4"] }
http = "0.2.8"
chrono = "0.4.22"
reqwest = { version = "0.11.12", features = ["json", "gzip"] }
reqwest-middleware = "0.1.6"
reqwest-retry = "0.1.5"
tokio-stream = "0.1.10"
log = "0.4.17"
async-trait = "0.1.57"
task-local-extensions = "0.1.3"
reqwest-tracing = "0.3.1"
rand = "0.8.5"
itertools = "0.10.5"
tokio = "1.21.2"
chrono-tz = "0.7.0"
rust-crypto = "0.2.36"
mime = "0.3.16"
anyhow = "1.0.65"
fern = "0.6.1"
utoipa = { version = "2.2.0", features = ["rocket_extras"] }
lazy_static = "1.4.0"

[build-dependencies]
vergen = "7.4.2"

# [patch.crates-io]
# libmaccas = { path = "/home/anurag/Projects/libmaccas-rs" }

[lib]
name = "maccas"
path = "src/lib.rs"

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "refresh"
path = "src/bin/refresh.rs"

[[bin]]
name = "cleanup"
path = "src/bin/cleanup.rs"

[[bin]]
name = "accounts"
path = "src/bin/accounts.rs"

[[bin]]
name = "images"
path = "src/bin/images.rs"

[profile.release-strip]
inherits = "release"
strip = "symbols"
