[workspace]
resolver = "2"
members = [
    "maccas",
    "accounts-cli",
    "libs/foundation",
    "libs/libmaccas-rs",
    "libs/places-rs",
]

[profile.release-strip]
inherits = "release"
strip = "symbols"

[workspace.dependencies]
aws-sdk-dynamodb = "0.36"
aws-sdk-s3 = "0.36"
aws-types = "0.57"
aws-sdk-sqs = "0.35"
aws-sdk-secretsmanager = "0.36"
aws-config = "0.57"

serde = "1.0.193"
serde_json = "1.0.108"
serde_derive = "1.0.190"
serde_dynamo = { version = "4.2.11", features = ["aws-sdk-dynamodb+0_36"] }

rocket = { version = "0.5.0", features = ["json", "uuid"] }
