[workspace]
resolver = "2"
members = [
    "api",
    "migration",
    "libmaccas",
    "places",
    "openai",
    "batch",
    "base",
    "event", 
    "sensordata/lib", 
    "migrate-audit",
]

[profile.release-strip]
inherits = "release"
strip = "symbols"

[workspace.dependencies]
async-graphql = { version = "7.0.11", features = [
    "uuid",
    "chrono",
    "dataloader",
    "log",
    "opentelemetry",
    "tracing",
] }

serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
rand = "0.8.5"
chrono = "0.4.38"

tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-futures = "0.2.5"
tracing-opentelemetry = "0.27.0"

sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
] }

anyhow = "1.0.91"

config = "0.14.0"

entity = { path = "./entity" }
libmaccas = { path = "./libmaccas" }
places = { path = "./places" }
openai = { path = "./openai" }
base = { path = "./base" }
converters = { path = "./converters" }
event = { path = "./event" }
batch = { path = "./batch" }
sensordata = { path = "./sensordata/lib" }

thiserror = "1.0.65"
futures = "0.3.31"
futures-util = "0.3.31"

reqwest = { version = "0.12", features = ["json", "gzip", "native-tls"] }
reqwest-middleware = { version = "0.3.3", features = ["json"] }
reqwest-retry = "0.6.1"
reqwest-tracing = { version = "0.5", features = ["opentelemetry_0_23"] }

async-trait = "0.1.83"

tokio = { version = "1.41.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "sync",
] }
tokio-util = "0.7.12"
cron = "0.12.1"
uuid = { version = "1.11", features = ["v4"] }
redis = { version = "0.27.5", features = [
    "tokio-comp",
    "aio",
    "connection-manager",
] }
axum = { version = "0.7.7", features = ["macros"] }
tower-http = { version = "0.6.1", features = ["trace", "cors"] }
itertools = "0.13.0"
opentelemetry = "0.26.0"
opentelemetry_sdk = "0.26.0"
http = "1.1.0"

