[workspace]
resolver = "2"
members = [
    "api",
    "migration",
    "external/libmaccas",
    "external/places",
    "external/openai",
    "batch",
    "base",
    "event",
]

[profile.release-strip]
inherits = "release"
strip = "symbols"

[workspace.dependencies]
async-graphql = { version = "7.0.3", features = [
    "uuid",
    "chrono",
    "dataloader",
    "log",
    "tracing",
    "opentelemetry",
] }

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
rand = "0.8.5"
chrono = "0.4.37"

tracing = "0.1.40"
tracing-subscriber = "0.3.18"

sea-orm = { version = "0.12", features = [
    "sqlx-postgres",
    "runtime-tokio-native-tls",
    "macros",
] }

anyhow = "1.0.81"

config = "0.14.0"

entity = { path = "./entity" }
libmaccas = { path = "./external/libmaccas" }
places = { path = "./external/places" }
openai = { path = "./external/openai" }
base = { path = "./base" }
converters = { path = "./converters" }
event = { path = "./event" }
batch = { path = "./batch" }

thiserror = "1.0.58"
futures = "0.3.30"

reqwest = { version = "0.12", features = ["json", "gzip", "native-tls"] }
reqwest-middleware = { version = "0.3.0", features = ["json"] }
reqwest-retry = "0.5.0"
reqwest-tracing = { version = "0.5.0", features = ["opentelemetry_0_21"] }

async-trait = "0.1.79"

tokio = { version = "1.37.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "sync",
] }
tokio-util = "0.7.10"
cron = "0.12.1"
uuid = { version = "1.8", features = ["v4"] }
redis = { version = "0.25.3", features = [
    "tokio-comp",
    "aio",
    "connection-manager",
] }
axum = { version = "0.7.5", features = ["macros"] }
tower-http = { version = "0.5.2", features = ["trace", "cors"] }
itertools = "0.12.1"
opentelemetry = "0.22.0"
old_http = { package = "http", version = "0.2.1" }
http = "1.0.0"

[patch.crates-io]
reqwest-middleware = { git = "https://github.com/TrueLayer/reqwest-middleware.git", branch = "main" }
reqwest-tracing = { git = "https://github.com/TrueLayer/reqwest-middleware.git", branch = "main" }
reqwest-retry = { git = "https://github.com/TrueLayer/reqwest-middleware.git", branch = "main" }
