name: "maccas-prod"
services:
  web:
    image: ghcr.io/accurate0/maccas-web:${SOURCE_COMMIT}
    expose:
      - 3000
    links:
      - "api:api"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - OLD_API_BASE_URL=https://api.maccas.one/v1
      - API_BASE_URL=http://api:8000/v1
      - DATABASE_URL=${WEB_DATABASE_URL}
      - ADDRESS_HEADER=CF-Connecting-IP

  dashboard:
    image: ghcr.io/accurate0/maccas-dashboard:${SOURCE_COMMIT}
    links:
      - "api:api"
      - "batch:batch"
      - "event:event"
    expose:
      - 3001
    depends_on:
      migration:
        condition: service_completed_successfully
      api:
        condition: service_healthy
      event:
        condition: service_healthy
      batch:
        condition: service_healthy
    environment:
      - API_BASE_URL=http://api:8000/v1
      - EVENT_API_BASE=http://event:8001
      - BATCH_API_BASE=http://batch:8002
      - DATABASE_URL=${DASHBOARD_DATABASE_URL}

  api:
    image: ghcr.io/accurate0/maccas-api:${SOURCE_COMMIT}
    links:
      - "event:event"
      - "batch:batch"
    expose:
      - 8000
    depends_on:
      migration:
        condition: service_completed_successfully
      event:
        condition: service_healthy
      batch:
        condition: service_healthy
    environment:
      - EVENT_API_BASE=http://event:8001
      - BATCH_API_BASE=http://batch:8002
      - DATABASE__URL=${MACCAS_DATABASE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1s

  event:
    image: ghcr.io/accurate0/maccas-event:${SOURCE_COMMIT}
    expose:
      - 8001
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - DATABASE__URL=${MACCAS_DATABASE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1s

  batch:
    image: ghcr.io/accurate0/maccas-batch:${SOURCE_COMMIT}
    expose:
      - 8002
    restart: unless-stopped
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - EVENT_API_BASE=http://event:8001
      - SENSORDATA_API_BASE=http://sensordata:8080/v1
      - DISABLE_JOBS=create-account,activate-account
      - DATABASE__URL=${MACCAS_DATABASE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1s

  migration:
    restart: on-failure
    image: ghcr.io/accurate0/maccas-migration:${SOURCE_COMMIT}
    environment:
      - DATABASE_URL=${MACCAS_DATABASE_URL}
