
version: '3'

services:
  web:
    build:
      context: web
    ports:
      - "3000:3000"
    links:
      - "api:api"
      - "db:database"
    depends_on:
      - api
    environment:
      - PUBLIC_API_BASE_URL=http://api:8000
      - DATABASE_URL=postgres://postgres:test@database/maccas-web
      - AUTH_SECRET=111

  api:
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=api
    ports:
      - "8000:8000"
    links:
      - "db:database"
    depends_on:
      - db
    environment:
      - DATABASE__URL=postgres://postgres:test@database/maccas
    env_file:
      - .env.local

  batch:
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=batch
    links:
      - "db:database"
    depends_on:
      - db
    environment:
      - DATABASE__URL=postgres://postgres:test@database/maccas
    env_file:
      - .env.local

  queue:
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=queue
    ports:
      - "8001:8000"
    links:
      - "db:database"
    depends_on:
      - db
    environment:
      - DATABASE__URL=postgres://postgres:test@database/maccas
    env_file:
      - .env.local

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: maccas

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data


volumes:
  pgdata:
  redisdata:
