
version: '3'

services:
  # api:
  #   build:
  #     dockerfile: Dockerfile.api
  #   ports:
  #     - "8000:8000"
  #   links:
  #     - "db:database"
  #   depends_on:
  #     - db

  #   environment:
  #     - DATABASE__URL=postgres://postgres:test@database/maccas

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: maccas

volumes:
  pgdata:
