
version: '3'

services:
  web:
    build:
      context: web
    ports:
      - "3000:3000"
    links:
      - "api:api"
      - "db:database"
    depends_on:
      - api
      - db
    environment:
      - OLD_API_BASE_URL=https://api.maccas.one/v1
      - API_BASE_URL=http://api:8000
      - DATABASE_URL=postgres://postgres:test@database/maccas-web
      - AUTH_SECRET=111
      # svelte needs orgin for csrf
      - ORIGIN=http://localhost:3000

  dashboard:
    build:
      context: dashboard
    ports:
      - "3001:3001"
    links:
      - "api:api"
      - "db:database"
      - "batch:batch"
      - "event:event"
    depends_on:
      - api
      - db
      - batch
      - event
    environment:
      - DATABASE_URL=postgres://postgres:test@database/maccas-dashboard
      - API_BASE_URL=http://api:8000
      - EVENT_API_BASE=http://event:8001
      - BATCH_API_BASE=http://batch:8002
      - AUTH_SECRET=111

  api:
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=api
    ports:
      - "8000:8000"
    links:
      - "db:database"
      - "event:event"
      - "batch:batch"
      - "cache:cache"
    depends_on:
      - db
      - cache
      - event
      - batch
    environment:
      - DATABASE__URL=postgres://postgres:test@database/maccas
      - EVENT_API_BASE=http://event:8001
      - BATCH_API_BASE=http://batch:8002
      - CACHE_CONNECTION_STRING=redis://cache:6379
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 1s

  event:
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=event
    ports:
      - "8001:8001"
    links:
      - "db:database"
      - "cache:cache"
    depends_on:
      - db
      - cache
    environment:
      - DATABASE__URL=postgres://postgres:test@database/maccas
      - CACHE_CONNECTION_STRING=redis://cache:6379
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 1s

  batch:
    build:
      dockerfile: Dockerfile
      args:
        - BINARY_NAME=batch
    ports:
      - "8002:8002"
    links:
      - "db:database"
    depends_on:
      - db
    environment:
      - DATABASE__URL=postgres://postgres:test@database/maccas
      - AUTH_SECRET=111
    env_file:
      - .env.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 1s

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: maccas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 90s
      timeout: 5s
      retries: 5

  cache:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data

volumes:
  pgdata:
  dragonflydata:
