apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sensordata-android-pvc
  namespace: maccas-api
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-replicated
  resources:
    requests:
      storage: 100Mi
