apiVersion: apps/v1
kind: Deployment
metadata:
  name: maccas-sensordata
  namespace: maccas-api
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: maccas-sensordata
  replicas: 1
  template:
    metadata:
      labels:
        app: maccas-sensordata
    spec:
      containers:
        - name: maccas-sensordata
          image: maccas-sensordata:latest
          imagePullPolicy: Always
          requests:
            limits:
              squat.ai/kvm: "1"
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          ports:
            - containerPort: 8080
