apiVersion: apps/v1
kind: Deployment
metadata:
  name: maccas-sensordata
  namespace: maccas-api
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: maccas-sensordata
  replicas: 1
  template:
    metadata:
      labels:
        app: maccas-sensordata
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-optiplex-5
      volumes:
        - name: android-device
          hostPath:
            path: /dev/bus/usb/001/019
      containers:
        - name: maccas-sensordata
          image: maccas-sensordata:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /dev/bus/usb/001/019
              name: android-device
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          ports:
            - containerPort: 8080
