apiVersion: v1
kind: Service
metadata:
  name: maccas-sensordata
  namespace: maccas-api
spec:
  selector:
    app: maccas-sensordata
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 8080
