# fly.toml app configuration file generated for maccas-event on 2024-01-26T16:40:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maccas-event'
primary_region = 'syd'

[build]
image = 'maccas-api-event'

[http_service]
internal_port = 8001
force_https = true
min_machines_running = 1
max_machines_running = 1

[checks]
[checks.healthcheck]
port = 8001
type = 'http'
interval = '15s'
timeout = '10s'
grace_period = '10s'
method = 'get'
path = '/health'

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
