apiVersion: apps/v1
kind: Deployment
metadata:
  name: maccas-scheduler
  namespace: maccas-api
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: maccas-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: maccas-scheduler
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: maccas-scheduler
              topologyKey: kubernetes.io/hostname
      containers:
        - name: maccas-scheduler
          image: maccas-scheduler:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /v1/health/self
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: EVENT_API_BASE
              value: http://maccas-event.maccas-api.svc.cluster.local:8001
          envFrom:
            - secretRef:
                name: maccas-common-managed-secrets
            - secretRef:
                name: maccas-api-managed-secrets
