apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: maccas-migration-secret
  namespace: maccas-api
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: maccas-api-576-r
        envSlug: prod
        secretsPath: "/migration"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: maccas-migration-managed-secrets
    secretNamespace: maccas-api
    creationPolicy: "Owner"
