apiVersion: v1
kind: Service
metadata:
  name: maccas-batch
  namespace: maccas-api
spec:
  selector:
    app: maccas-batch
  ports:
    - name: api
      protocol: TCP
      port: 8002
      targetPort: 8002
