[package]
name = "openai"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }


reqwest = { workspace = true }
uuid = { version = "1.8.0", features = ["v4"] }
http = "1.1"
reqwest-middleware = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
