[package]
name = "accounts-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }

aws-sdk-dynamodb = "0.28.0"

maccas = { path = "../maccas" }
foundation = { path = "../foundation" }
log = "0.4.19"
tokio = { version = "1.29.1", features = ["macros"] }
anyhow = "1.0.72"
serde_json = "1.0.104"
libmaccas = "0.47.0"
rand = "0.8.5"
petname = "1.1.3"
titlecase = "2.2.1"
regex = "1.9.1"
imap = "2.4.1"
native-tls = "0.2.11"
