apiVersion: apps/v1
kind: Deployment
metadata:
  name: maccas-graphql
  namespace: maccas-api
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: maccas-graphql
  replicas: 3
  template:
    metadata:
      labels:
        app: maccas-graphql
    spec:
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: maccas-graphql
          whenUnsatisfiable: ScheduleAnyway

      initContainers:
        - name: maccas-migration
          image: maccas-migration:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: maccas-migration-managed-secrets
      containers:
        - name: maccas-graphql
          image: maccas-graphql:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /v1/health/self
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: EVENT_API_BASE
              value: http://maccas-event.maccas-api.svc.cluster.local:8001
            - name: RECOMMENDATIONS_API_BASE
              value: http://maccas-recommendations.maccas-api.svc.cluster.local:8003
            - name: FLIPT_URL
              value: http://flipt.flipt.svc.cluster.local:8080
          envFrom:
            - secretRef:
                name: maccas-common-managed-secrets
            - secretRef:
                name: maccas-api-managed-secrets
          ports:
            - containerPort: 8000
