query Index($includePoints: Boolean!, $minimumCurrentPoints: Int!) {
	offers {
		shortName
		imageBasename
		name
		count
		offerPropositionId
		validFrom
		validTo
	}
	points(filter: { minimumCurrentPoints: $minimumCurrentPoints }) @include(if: $includePoints) {
		currentPoints
		accountId
	}
}
