[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
tracing = { workspace = true }
reqwest-retry = { workspace = true }
reqwest-tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
config = { workspace = true }
