[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
tracing = { workspace = true }
reqwest-retry = { workspace = true }
reqwest-tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
config = { workspace = true }
sea-orm = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
cron = { workspace = true }
entity = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
task-local-extensions = "0.1.4"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
