apiVersion: apps/v1
kind: Deployment
metadata:
  name: maccas-event
  namespace: maccas-api
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: maccas-event
  replicas: 1
  template:
    metadata:
      labels:
        app: maccas-event
    spec:
      initContainers:
        - name: maccas-migration
          image: maccas-migration:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: maccas-migration-managed-secrets
      containers:
        - name: maccas-event
          image: maccas-event:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: maccas-common-managed-secrets
            - secretRef:
                name: maccas-api-managed-secrets
          ports:
            - containerPort: 8001
