apiVersion: v1
kind: Service
metadata:
  name: maccas-event
  namespace: maccas-api
spec:
  selector:
    app: maccas-event
  ports:
    - name: api
      protocol: TCP
      port: 8001
      targetPort: 8001
