[package]
name = "delayqueue"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
pgmq = "0.30.0"
serde_json = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
sea-orm = { workspace = true }
