[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { workspace = true }
async-graphql-axum = "6.0.11"

axum = "0.7.2"

tokio = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

sea-orm = { workspace = true }
anyhow = { workspace = true }

config = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
tower-http = { version = "0.5.0", features = ["trace"] }

entity = { workspace = true }
libmaccas = { workspace = true }
async-trait = { workspace = true }
base = { workspace = true }
log = { workspace = true }
