[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { workspace = true }
async-graphql-axum = "6.0.11"

axum = { version = "0.6.20", features = ["macros"] }

tokio = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

sea-orm = { workspace = true }
anyhow = { workspace = true }

config = { workspace = true }

serde = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tower-http = { version = "0.4.4", features = ["trace", "cors"] }

entity = { workspace = true }
libmaccas = { workspace = true }
places = { workspace = true }
async-trait = { workspace = true }
base = { workspace = true }
log = { workspace = true }
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
