app = 'maccas-api'
primary_region = 'syd'

[http_service]
internal_port = 8000
force_https = true
min_machines_running = 1
auto_stop_machines = true
auto_start_machines = true

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 512

[build]
image = "maccas-api-api"

[checks]
[checks.healthcheck]
grace_period = "10s"
interval = "15s"
method = "get"
path = "/v1/health"
port = 8000
timeout = "10s"
type = "http"

[env]
EVENT_API_BASE = "http://maccas-event.internal:8001"
BATCH_API_BASE = "http://maccas-batch.internal:8002"
