name: api
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - API/**
      - .github/workflows/api.yml

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: "general-api-group"
          template: ./API/maccas-api-v2-deploy.json
