on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images

    permissions:
      packages: write

    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "maccas-*"
          image-tags: "!latest"
          keep-n-most-recent: 3
          cut-off: 2w
          dry-run: true
