name: infra-dev
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/infra-dev.yml"

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    permissions:
      id-token: write
    environment: development-infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    name: deploy infra

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: terraform init
        run: terraform init -backend-config="key=maccas/dev/api-gateway.tfstate"
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        run: terraform apply -input=false -auto-approve
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_AWS_API_GATEWAY_ID: ${{ secrets.AWS_API_GATEWAY_ID }}
          TF_VAR_AWS_INTEGRATION_ID: ${{ secrets.AWS_INTEGRATION_ID }}
          TF_VAR_AWS_AUTHORIZER_ID: ${{ secrets.AWS_AUTHORIZER_ID }}
