name: lambda
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "API/**"
      - ".vscode/**"

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1
        with:
          key: lambda

      - name: rust-cargo-install
        uses: actions-rs/install@v0.1.2
        with:
          crate: cargo-lambda
          version: 0.6.1
          use-tool-cache: true

      - name: install zig
        run: pip3 install ziglang

      - name: cargo build api
        run: cargo lambda build --release --target x86_64-unknown-linux-musl --output-format zip --bin api

      - name: publish lambda ${{ inputs.lambda_name }}
        run: aws lambda update-function-code --function-name MaccasApi-v2 --zip-file fileb://target/lambda/api/bootstrap.zip --region ap-southeast-2

      - name: cargo build refresh
        run: cargo lambda build --release --target x86_64-unknown-linux-musl --output-format zip --bin refresh

      - uses: actions/upload-artifact@v3
        with:
          name: refresh
          path: ./target/lambda/refresh/bootstrap.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region:
          - ap-southeast-2
          - ap-southeast-1
          - ap-northeast-1
          - ap-northeast-2

    name: deploy ${{ matrix.region }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: refresh

      - name: deploy ${{ matrix.region }}
        run: aws lambda update-function-code --function-name MaccasApi-refresh-v2 --zip-file fileb://bootstrap.zip --region ${{ matrix.region }}
