name: lambda-dev
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - ".github/dependabot.yml"
      - ".vscode/**"
      - "infra/**"
      - "resources/**"

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-deploy:
    environment: development
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: install musl gcc
        run: sudo apt install musl-tools

      - uses: actions/checkout@v3
      - uses: Accurate0/rust-toolchain@main
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-dev

      - name: cargo build
        run: cargo build --locked --target x86_64-unknown-linux-musl --bin api

      - name: create zip
        run: |
          mv ./target/x86_64-unknown-linux-musl/debug/api ./bootstrap
          strip ./bootstrap
          zip -r bootstrap.zip ./bootstrap

      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: deploy dev
        run: aws lambda update-function-code --function-name MaccasApi-api-dev --zip-file fileb://bootstrap.zip --region ap-southeast-2

  upload-config:
    permissions:
      id-token: write
    needs: [build-deploy]
    runs-on: ubuntu-latest
    name: upload config

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/checkout@v3
      - uses: Accurate0/modify-json@v1.1.0
        with:
          __inputFile: ./config.json
          __outputFile: ./base-config.json
          mcdonalds__client_id: ${{ secrets.API_CONFIG_CLIENT_ID }}
          mcdonalds__client_secret: ${{ secrets.API_CONFIG_CLIENT_SECRET }}
          mcdonalds__sensor_data: ${{ secrets.API_CONFIG_SENSOR_DATA }}
          mcdonalds__service_account_name: ${{ secrets.API_CONFIG_SERVICE_ACCOUNT_NAME }}
          api__jwt__jwks_url: ${{ secrets.API_CONFIG_JWKS_URL }}
          api__discord_deal_use__webhooks__0: ${{ secrets.API_CONFIG_DISCORD_WEBHOOK_ELLIOT }}
          api__discord_deal_use__webhooks__1: ${{ secrets.API_CONFIG_DISCORD_WEBHOOK_KEVIN }}
          refresh__discord_error__webhooks__0: ${{ secrets.API_CONFIG_DISCORD_WEBHOOK_SERVICE }}
          proxy__username: ${{ secrets.API_CONFIG_REFRESH_PROXY_USERNAME }}
          proxy__password: ${{ secrets.API_CONFIG_REFRESH_PROXY_PASSWORD }}
          proxy__address: ${{ secrets.API_CONFIG_REFRESH_PROXY_ADDRESS }}
          accounts__email__address: ${{ secrets.API_CONFIG_ACCOUNTS_EMAIL }}
          accounts__email__password: ${{ secrets.API_CONFIG_ACCOUNTS_PASSWORD }}
          accounts__domain_name: ${{ secrets.API_CONFIG_ACCOUNTS_DOMAIN_NAME }}
      - name: upload to s3
        run: aws s3 cp base-config.json s3://maccas-application-config/base-config-dev.json
