name: lambda
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "API/**"
      - ".github/dependabot.yml"
      - ".vscode/**"

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install musl gcc
        run: sudo apt install musl-tools

      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: cargo build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: create zip (api)
        run: |
          mv ./target/x86_64-unknown-linux-musl/release/api ./bootstrap
          strip ./bootstrap
          zip -r bootstrap.zip ./bootstrap

      - name: upload api artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ./bootstrap.zip

      - name: remove zip (api)
        run: |
          rm -f ./bootstrap.zip

      - name: create zip (service)
        run: |
          mv ./target/x86_64-unknown-linux-musl/release/service ./bootstrap
          strip ./bootstrap
          zip -r bootstrap.zip ./bootstrap

      - name: upload service artifact
        uses: actions/upload-artifact@v3
        with:
          name: service
          path: ./bootstrap.zip

      - name: remove zip (service)
        run: |
          rm -f ./bootstrap.zip

  deploy-api:
    needs: build
    runs-on: ubuntu-latest

    name: deploy api
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: api

      - name: deploy api
        run: aws lambda update-function-code --function-name MaccasApi-v2 --zip-file fileb://bootstrap.zip --region ap-southeast-2

  deploy-refresh:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region:
          - ap-southeast-2
          - ap-southeast-1
          - ap-northeast-1
          - ap-northeast-2

    name: deploy ${{ matrix.region }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: service

      - name: deploy ${{ matrix.region }}
        run: aws lambda update-function-code --function-name MaccasApi-refresh-v2 --zip-file fileb://bootstrap.zip --region ${{ matrix.region }}
