name: lambda
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "API/**"
      - ".github/dependabot.yml"
      - ".vscode/**"

concurrency:
  group: environment-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install musl gcc
        run: sudo apt install musl-tools

      - uses: actions/checkout@v2
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo build
        run: cargo build --locked --release --target x86_64-unknown-linux-musl

      - name: create zip
        run: |
          mkdir ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release/api ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release/refresh ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release/cleanup ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release/accounts ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release/images ./maccas-api

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: maccas-api
          path: ./maccas-api

  artifacts:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - api
          - accounts
          - cleanup
          - images
          - refresh

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: maccas-api

      - name: create zip (${{ matrix.task }})
        run: |
          tree
          mv ./maccas-api/${{ matrix.task }} ./bootstrap
          strip ./bootstrap
          zip -r bootstrap.zip ./bootstrap

      - name: upload ${{ matrix.task }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.task }}
          path: ./bootstrap.zip

  deploy:
    needs: artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - accounts
          - cleanup
          - images
          - api
          - refresh

    name: deploy ${{ matrix.task }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.task }}

      - name: deploy ${{ matrix.task }}
        run: aws lambda update-function-code --function-name MaccasApi-${{ matrix.task }} --zip-file fileb://bootstrap.zip --region ap-southeast-2

      - name: deploy ${{ matrix.task }} (ap-southeast-1)
        if: ${{ ${{ matrix.task }} == 'refresh' }}
        run: aws lambda update-function-code --function-name MaccasApi-${{ matrix.task }} --zip-file fileb://bootstrap.zip --region ap-southeast-1

  upload-config:
    needs: [deploy]
    runs-on: ubuntu-latest
    name: upload config
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-2

    steps:
      - uses: actions/checkout@v2
      - uses: Accurate0/modify-json@v1.1.0
        with:
          __inputFile: ./config.json
          __outputFile: ./base-config.json
          api__api_key: ${{ secrets.API_CONFIG_API_KEY }}
          mcdonalds__client_id: ${{ secrets.API_CONFIG_CLIENT_ID }}
          mcdonalds__client_secret: ${{ secrets.API_CONFIG_CLIENT_SECRET }}
          mcdonalds__sensor_data: ${{ secrets.API_CONFIG_SENSOR_DATA }}
          mcdonalds__service_account__account_name: ${{ secrets.API_CONFIG_SERVICE_ACCOUNT_NAME }}
          mcdonalds__service_account__login_username: ${{ secrets.API_CONFIG_SERVICE_USERNAME }}
          mcdonalds__service_account__login_password: ${{ secrets.API_CONFIG_SERVICE_PASSWORD }}
          api__jwt__bypass_key: ${{ secrets.API_CONFIG_JWT_BYPASS_KEY }}
          api__discord_deal_use__webhooks__0: ${{ secrets.API_CONFIG_DISCORD_WEBHOOK_ELLIOT }}
          api__discord_deal_use__webhooks__1: ${{ secrets.API_CONFIG_DISCORD_WEBHOOK_KEVIN }}
          refresh__discord__error__webhooks__0: ${{ secrets.API_CONFIG_DISCORD_WEBHOOK_SERVICE }}
          accounts__email: ${{ secrets.API_CONFIG_ACCOUNTS_EMAIL }}
          accounts__password: ${{ secrets.API_CONFIG_ACCOUNTS_PASSWORD }}
      - name: upload to s3
        run: aws s3 cp base-config.json s3://maccas-application-config/base-config.json
