name: lambda
on:
  workflow_dispatch:
  push:
    branches: [main, v2.x]
    paths-ignore:
      - ".github/dependabot.yml"
      - ".vscode/**"
      - "infra/**"
      - "resources/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install musl gcc
        run: sudo apt install musl-tools

      - uses: actions/checkout@v4
      - uses: Accurate0/rust-toolchain@main
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1

      - name: cargo build
        run: cargo build --locked --profile release-strip --target x86_64-unknown-linux-musl

      - name: copy artifacts
        run: |
          mkdir ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release-strip/api ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release-strip/refresh ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release-strip/refresh-failure ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release-strip/cleanup ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release-strip/images ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release-strip/accounts ./maccas-api
          cp ./target/x86_64-unknown-linux-musl/release-strip/jwt ./maccas-api

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: maccas-api
          path: ./maccas-api

  artifacts:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - api
          - cleanup
          - images
          - refresh
          - refresh-failure
          - accounts
          - jwt

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: maccas-api

      - name: create zip (${{ matrix.task }})
        run: |
          mv ./${{ matrix.task }} ./bootstrap
          zip -r bootstrap.zip ./bootstrap

      - name: upload ${{ matrix.task }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.task }}
          path: ./bootstrap.zip

  deploy-api:
    permissions:
      id-token: write
    needs: artifacts
    environment: production-api
    runs-on: ubuntu-latest

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: api

      - name: deploy api
        run: aws lambda update-function-code --function-name MaccasApi-api --zip-file fileb://bootstrap.zip --region ap-southeast-2

  deploy-cleanup:
    permissions:
      id-token: write
    needs: artifacts
    environment: production-cleanup
    runs-on: ubuntu-latest

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: cleanup

      - name: deploy cleanup
        run: aws lambda update-function-code --function-name MaccasApi-cleanup --zip-file fileb://bootstrap.zip --region ap-southeast-2

  deploy-images:
    permissions:
      id-token: write
    needs: artifacts
    environment: production-images
    runs-on: ubuntu-latest

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: images

      - name: deploy images
        run: aws lambda update-function-code --function-name MaccasApi-images --zip-file fileb://bootstrap.zip --region ap-southeast-2

  deploy-refresh:
    permissions:
      id-token: write
    needs: artifacts
    environment: production-refresh
    runs-on: ubuntu-latest

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: refresh

      - name: deploy refresh
        run: aws lambda update-function-code --function-name MaccasApi-refresh --zip-file fileb://bootstrap.zip --region ap-southeast-2

      - name: deploy refresh (ap-southeast-1)
        run: aws lambda update-function-code --function-name MaccasApi-refresh --zip-file fileb://bootstrap.zip --region ap-southeast-1

      - name: deploy refresh (ap-southeast-4)
        run: aws lambda update-function-code --function-name MaccasApi-refresh --zip-file fileb://bootstrap.zip --region ap-southeast-4

  deploy-refresh-failure:
    permissions:
      id-token: write
    needs: artifacts
    environment: production-refresh-failure
    runs-on: ubuntu-latest

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: refresh-failure

      - name: deploy refresh-failure
        run: aws lambda update-function-code --function-name MaccasApi-refresh-failure --zip-file fileb://bootstrap.zip --region ap-southeast-2

  deploy-accounts:
    permissions:
      id-token: write
    needs: artifacts
    environment: production-accounts
    runs-on: ubuntu-latest

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: accounts

      - name: deploy accounts
        run: aws lambda update-function-code --function-name MaccasApi-accounts --zip-file fileb://bootstrap.zip --region ap-southeast-2

  deploy-jwt:
    permissions:
      id-token: write
    needs: artifacts
    environment: production-jwt
    runs-on: ubuntu-latest

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/download-artifact@v3
        with:
          name: jwt

      - name: deploy jwt
        run: aws lambda update-function-code --function-name MaccasApi-jwt --zip-file fileb://bootstrap.zip --region ap-southeast-2

  upload-config:
    permissions:
      id-token: write
    needs: artifacts
    environment: production-config
    runs-on: ubuntu-latest
    name: upload config

    steps:
      - name: configure oicd aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: actions/checkout@v4
      - uses: Accurate0/modify-json@v1.1.0
        with:
          __inputFile: ./config.json
          __outputFile: ./base-config.json
          mcdonalds__client_id: ${{ secrets.API_CONFIG_CLIENT_ID }}
          mcdonalds__client_secret: ${{ secrets.API_CONFIG_CLIENT_SECRET }}
          mcdonalds__sensor_data: ${{ secrets.API_CONFIG_SENSOR_DATA }}
          mcdonalds__service_account_name: ${{ secrets.API_CONFIG_SERVICE_ACCOUNT_NAME }}
          proxy__username: ${{ secrets.API_CONFIG_REFRESH_PROXY_USERNAME }}
          proxy__password: ${{ secrets.API_CONFIG_REFRESH_PROXY_PASSWORD }}
          proxy__address: ${{ secrets.API_CONFIG_REFRESH_PROXY_ADDRESS }}
          accounts__email__address: ${{ secrets.API_CONFIG_ACCOUNTS_EMAIL }}
          accounts__email__password: ${{ secrets.API_CONFIG_ACCOUNTS_PASSWORD }}
          accounts__domain_name: ${{ secrets.API_CONFIG_ACCOUNTS_DOMAIN_NAME }}
      - name: upload to s3
        run: aws s3 cp base-config.json s3://maccas-application-config/base-config.json
