name: PR & Push Build
on:
  pull_request:
  push:
    branches-ignore:
      - main
      - v1
      - v2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        apps: [api, web, migration, recommendations, clustering]

    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build
        if: ${{ matrix.apps  == 'api' || matrix.apps == 'migration' || matrix.apps == 'recommendations' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          build-args: |
            BINARY_NAME=${{ matrix.apps }}

      - name: Docker build
        if: ${{ matrix.apps  == 'web' || matrix.apps == 'clustering' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.apps }}
          push: false
          build-args: |
            BINARY_NAME=${{ matrix.apps }}
