name: PR Build
on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        apps: [graphql, batch, dashboard, event, web, migration]

    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build
        if: ${{ matrix.apps  == 'api' || matrix.apps  == 'batch' || matrix.apps  == 'event' || matrix.apps == 'migration' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          build-args: |
            BINARY_NAME=${{ matrix.apps }}

      - name: Docker build
        if: ${{ matrix.apps  == 'dashboard' || matrix.apps  == 'web' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.apps }}
          push: false
          build-args: |
            BINARY_NAME=${{ matrix.apps }}
