//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "jobs")]
pub struct Model {
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub last_execution: Option<DateTime>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub context: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::job_history::Entity")]
    JobHistory,
}

impl Related<super::job_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JobHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
