//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod account_lock;
pub mod accounts;
pub mod categories;
pub mod events;
pub mod job_history;
pub mod jobs;
pub mod offer_audit;
pub mod offer_details;
pub mod offer_history;
pub mod offer_similarity;
pub mod offers;
pub mod points;
pub mod recommendations;
pub mod sea_orm_active_enums;
pub mod stores;
