//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::accounts::Entity as Accounts;
pub use super::current_jobs::Entity as CurrentJobs;
pub use super::jobs::Entity as Jobs;
pub use super::offers::Entity as Offers;
