//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::account_lock::Entity as AccountLock;
pub use super::accounts::Entity as Accounts;
pub use super::categories::Entity as Categories;
pub use super::events::Entity as Events;
pub use super::job_history::Entity as JobHistory;
pub use super::jobs::Entity as Jobs;
pub use super::offer_audit::Entity as OfferAudit;
pub use super::offer_details::Entity as OfferDetails;
pub use super::offer_embeddings::Entity as OfferEmbeddings;
pub use super::offer_history::Entity as OfferHistory;
pub use super::offer_name_cluster_association::Entity as OfferNameClusterAssociation;
pub use super::offer_similarity::Entity as OfferSimilarity;
pub use super::offers::Entity as Offers;
pub use super::points::Entity as Points;
pub use super::recommendations::Entity as Recommendations;
pub use super::stores::Entity as Stores;
