app = 'maccas-web'
primary_region = 'syd'

[build]
image = "maccas-api-web"

[http_service]
internal_port = 3000
force_https = true
min_machines_running = 1
auto_stop_machines = true
auto_start_machines = true
[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 512

[env]
OLD_API_BASE_URL = "https://api.maccas.one/v1"
API_BASE_URL = "http://maccas-api.internal:8000/v1"
ORIGIN = "https://maccas.one"
ADDRESS_HEADER = "Fly-Client-IP"

[deploy]
strategy = "canary"
release_command = "pnpm prisma migrate deploy"

[checks]
[checks.healthcheck]
grace_period = "10s"
interval = "15s"
method = "get"
path = "/health"
port = 3000
timeout = "10s"
type = "http"
