app = 'maccas-web'
primary_region = 'syd'

[build]
image = "maccas-api-web"

[http_service]
internal_port = 3000
force_https = true
min_machines_running = 1
max_machines_running = 1

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024

[env]
OLD_API_BASE_URL = "https://api.maccas.one/v1"
API_BASE_URL = "http://maccas-api.internal:8000"
ORIGIN = "https://next.maccas.one"

[deploy]
release_command = "pnpm prisma migrate deploy"
